### ISSUE TITLE
Comportement different du forcepod entre Theodore et DCMOTO

### ISSUE THREAD

**Issue by yoanrhk** [wide-dot/thomson-to8-game-engine#12]
Comportement normale (et observé sous DCMOTO) : Lorsque le forcepod est init, il apparait de la gauche de l'ecran et se dirige vers le centre (Position tracking)

Comportement observé sous Theodore : Le forcepod est en mode player 1 tracking au lieu d'etre en position tracking.

**Comment by yoanrhk** [comment]
Le bouton B est apparement "pressé" en debut de partie sous Theodore (pas sous DCMOTO)

        lda   Fire_Press
        anda  #c1_button_B_mask

Ceci renvoie une valeur non nulle, meme si le bouton B n'est pas pressé.

Un fix consiste a effacer la valeur de Fire_Press a l'init du forcepod (donc, juste une fois) pour eviter que le forcepod rentre en player 1 tracking,

**Comment by Samuel-DEVULDER** [comment]
Ca sent le bout de code pas initialisé pareil suivant les émuls ($00 vs $FF pour les RAMs au boot)
