### ISSUE TITLE
Le forcepod est mal positionné par rapport au vaisseau

### ISSUE THREAD

**Issue by bhrousseau** [wide-dot/thomson-to8-game-engine#22]
![Image](https://user-images.githubusercontent.com/56814489/230709223-d81de3de-78df-4be0-a3ac-41de87cbf88f.png)

**Comment by yoanrhk** [comment]
Front hook position fixed, matching arcade (ie one pixel over player1). Back hook position in proper position. Verified both with the arcade back and front positions.
